# Generated by Django 2.2.1 on 2020-03-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200326_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='numerical_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
