# Generated by Django 2.2.1 on 2020-03-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200329_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='answers_all',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='questions_all',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
