# Generated by Django 2.2.1 on 2020-03-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200329_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
