# Generated by Django 2.2.1 on 2020-04-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_history_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='numerical_value',
        ),
    ]
